from django.db import models
from django.conf import settings

# message model
# reference_id is unique identifier between 2 users
# message_text is text contained within a message
# message_sender is identified via the token of the user who is sending the message
# created data is automatically generated by server
# reaction is string of how the other user reacted
class Message(models.Model):
    reference_id = models.CharField(max_length=200, blank=False)
    message_text = models.CharField(max_length=5000, blank=False)
    message_sender = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        null=True,
        blank=True,
        related_name="message_sender",
        on_delete=models.CASCADE,
        auto_created=True
    )
    created_date = models.DateTimeField(auto_now_add=True)
    reaction = models.CharField(max_length=200, blank=True)

class Meta:
    ordering = ['created_date']